
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: youtube entertainment bot

# on: [push]
#   name: Do things every 10 minute
# on:
#   schedule:
#     - cron: "* */8 * * *"
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
#     name: Upgraded YT Generator
    steps:
#     - name: Successful
#       id: hello
#       uses: anugrah2002/Entertainment_News@master

# name: Do things every 10 minutes
# on:
#   schedule:
#     - cron: "*/10 * * * *"


    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Cache pip
      uses: actions/cache@v2
      with:
      
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        pip install flake8 
        python -m pip install --upgrade gtts
        python -m pip install --upgrade gtts-token
        pip install cloudinary
        pip install opencv-python
        pip install -r requirements.txt
        pip install firebase
        sudo apt-get install libsndfile1
        pip install testpath == 0.4
        pip install httplib2==0.15.0
        pip install google-api-python-client==1.6
        pip install firebase-admin
        sudo apt-get install libegl1\
            libopus0\
            libwoff1\
            libharfbuzz-icu0\
            libgstreamer-plugins-base1.0-0\
            libgstreamer-gl1.0-0\
            libgstreamer-plugins-bad1.0-0\
            libopenjp2-7\
            libwebpdemux2\
            libenchant1c2a\
            libhyphen0\
            libgles2\
            gstreamer1.0-libav
        pip install gcloud
        pip install sseclient
        pip install pycryptodome
        pip install requests-toolbelt
        pip install moviepy
        pip install ez_setup
        pip install flake8 
        pip install opencv-python
        
        
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
# pip install flake8 

    - name: runing views.py 
      run: |
        python views.py
