
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: youtube entertainment bot


# uncommment or comment below lines for activating or deactivating the cron job 
on:
  schedule:
    - cron: "* */1 * * *"
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
#     name: Upgraded YT Generator
    steps:
#     - name: Successful
#       id: hello
#       uses: anugrah2002/Entertainment_News@master

# name: Do things every 10 minutes
# on:
#   schedule:
#     - cron: "*/10 * * * *"


    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache pip
      uses: actions/cache@v2
      with:
      
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
          
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
        
    - name: Install dependencies
      run: |
        pip install flake8 
        python -m pip install --upgrade gtts
        python -m pip install --upgrade gtts-token
        pip install cloudinary
        pip install opencv-python
        pip install -r requirements.txt
        pip install firebase
        pip install firebase-admin
        pip install httplib2==0.15.0
        pip install google-api-python-client==1.7.11
        sudo apt-get install libegl1\
            libopus0\
            libwoff1\
            libharfbuzz-icu0\
            libgstreamer-plugins-base1.0-0\
            libgstreamer-gl1.0-0\
            libgstreamer-plugins-bad1.0-0\
            libopenjp2-7\
            libwebpdemux2\
            libenchant1c2a\
            libhyphen0\
            libgles2\
            gstreamer1.0-libav
        pip install moviepy
        pip install ez_setup
        pip install flake8 
        sudo apt-get install libsndfile1
        
        
        
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
# pip install flake8 

    - name: runing views.py 
      run: |
        python views.py
        
    - name: runing cleanupfunction.py
      run: |
        python cleanupfunction.py

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: /home/runner/work/EntertainmentNews_FromAjjtk/EntertainmentNews_FromAjjtk/final.mp4
